
common: &common
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: password
  port: 5432
  reconnect: true
  pool: 10
  prepared_statements: false

development:
  <<: *common
  database: app_development

test:
  <<: *common
  database: app_test